# Netlify configuration file
[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18" }

# SPA routing - redirect all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxying to backend
[[redirects]]
  from = "/api/*"
  to = "https://vmptime-backend.onrender.com/api/:splat"
  status = 200
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Environment variables
[template.environment]
  VITE_API_URL = "Backend API URL (e.g., https://vmptime-backend.onrender.com/api)"