# Render configuration for static site deployment
services:
  - type: static
    name: vm-prime-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://vmptime-backend.onrender.com/api
      - key: NODE_VERSION
        value: 18
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
    routes:
      - type: rewrite
        source: /api/(.*)
        destination: https://vmptime-backend.onrender.com/api/$1
      - type: rewrite
        source: /*
        destination: /index.html